#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_BREW=false
RUN_CURSOR=false
RUN_RAYCAST=false
RUN_MACOS=false
RUN_APP_STORE=false

usage() {
  cat <<'EOF'
Usage: scripts/snapshot.sh [options]

Refresh safe, whitelisted machine inventory in this repo.

Options:
  --all                 Refresh every supported inventory. Default when no options are passed.
  --brew                Refresh Brewfile from Homebrew.
  --cursor              Refresh scripts/cursor-extensions.sh from installed Cursor extensions.
  --raycast             Refresh docs/raycast-extensions.generated.txt.
  --macos-defaults      Refresh docs/macos-defaults.generated.md.
  --app-store           Refresh docs/app-store-apps.generated.txt from mas.
  -h, --help            Show this help message.

This script intentionally does not copy auth databases, keychains, tokens, SSH keys,
workspace history, Raycast encrypted state, or Cursor workspace/global storage.
EOF
}

if [[ $# -eq 0 ]]; then
  RUN_BREW=true
  RUN_CURSOR=true
  RUN_RAYCAST=true
  RUN_MACOS=true
  RUN_APP_STORE=true
fi

while [[ $# -gt 0 ]]; do
  case "$1" in
    --all)
      RUN_BREW=true
      RUN_CURSOR=true
      RUN_RAYCAST=true
      RUN_MACOS=true
      RUN_APP_STORE=true
      shift
      ;;
    --brew)
      RUN_BREW=true
      shift
      ;;
    --cursor)
      RUN_CURSOR=true
      shift
      ;;
    --raycast)
      RUN_RAYCAST=true
      shift
      ;;
    --macos-defaults)
      RUN_MACOS=true
      shift
      ;;
    --app-store)
      RUN_APP_STORE=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

has_command() {
  command -v "$1" >/dev/null 2>&1
}

write_if_changed() {
  local target="$1"
  local temp_file="$2"

  if [[ -f "$target" ]] && cmp -s "$temp_file" "$target"; then
    rm -f "$temp_file"
    echo "Already current: ${target#"$ROOT_DIR"/}"
    return
  fi

  mkdir -p "$(dirname "$target")"
  mv "$temp_file" "$target"
  echo "Updated: ${target#"$ROOT_DIR"/}"
}

snapshot_brew() {
  if ! has_command brew; then
    echo "Skipping Brewfile: brew is missing" >&2
    return
  fi

  brew bundle dump --force --file "$ROOT_DIR/Brewfile"
  ensure_brewfile_entry 'brew "mas"'
  ensure_brewfile_entry 'cask "conductor"'
  echo "Updated: Brewfile"
}

ensure_brewfile_entry() {
  local entry="$1"

  if ! grep -Fxq "$entry" "$ROOT_DIR/Brewfile"; then
    printf '\n%s\n' "$entry" >>"$ROOT_DIR/Brewfile"
    echo "Preserved Brewfile entry: $entry"
  fi
}

snapshot_cursor_extensions() {
  if ! has_command cursor; then
    echo "Skipping Cursor extensions: cursor CLI is missing" >&2
    return
  fi

  local temp_file
  temp_file="$(mktemp)"

  {
    cat <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

if ! command -v cursor >/dev/null 2>&1; then
  echo "Cursor CLI is missing. Install Cursor from Brewfile first." >&2
  exit 1
fi

extensions=(
EOF
    cursor --list-extensions | sort -f | while IFS= read -r extension; do
      [[ -n "$extension" ]] || continue
      printf '  %s\n' "$extension"
    done
    cat <<'EOF'
)

for extension in "${extensions[@]}"; do
  cursor --install-extension "$extension"
done

"$(dirname "$0")/cursor-config.sh"
EOF
  } >"$temp_file"

  write_if_changed "$ROOT_DIR/scripts/cursor-extensions.sh" "$temp_file"
  chmod +x "$ROOT_DIR/scripts/cursor-extensions.sh"
}

snapshot_raycast_extensions() {
  local extensions_dir="$HOME/.config/raycast/extensions"
  local target="$ROOT_DIR/docs/raycast-extensions.generated.txt"
  local temp_file
  temp_file="$(mktemp)"

  if [[ ! -d "$extensions_dir" ]]; then
    echo "Skipping Raycast extensions: $extensions_dir is missing" >&2
    rm -f "$temp_file"
    return
  fi

  {
    echo "# Generated by scripts/snapshot.sh --raycast"
    echo
    find "$extensions_dir" -mindepth 1 -maxdepth 1 -type d -print0 |
      while IFS= read -r -d '' extension_dir; do
        basename "$extension_dir"
      done |
      sort -f
  } >"$temp_file"

  write_if_changed "$target" "$temp_file"
}

read_default() {
  local domain="$1"
  local key="$2"

  defaults read "$domain" "$key" 2>/dev/null || printf '%s' "<unset>"
}

write_defaults_section() {
  local title="$1"
  shift

  printf '## %s\n\n' "$title"
  printf '| Domain | Key | Value |\n'
  printf '| --- | --- | --- |\n'

  local entry
  for entry in "$@"; do
    local domain="${entry%%	*}"
    local key="${entry#*	}"
    local value
    value="$(read_default "$domain" "$key")"
    value="${value//$'\n'/ }"
    printf "| \`%s\` | \`%s\` | \`%s\` |\n" "$domain" "$key" "$value"
  done
  printf '\n'
}

snapshot_macos_defaults() {
  if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "Skipping macOS defaults: not running on macOS" >&2
    return
  fi

  local target="$ROOT_DIR/docs/macos-defaults.generated.md"
  local temp_file
  temp_file="$(mktemp)"

  {
    echo "# Generated macOS Defaults"
    echo
    echo "Generated by scripts/snapshot.sh --macos-defaults."
    echo
    write_defaults_section "Global" \
      $'NSGlobalDomain	InitialKeyRepeat' \
      $'NSGlobalDomain	KeyRepeat' \
      $'NSGlobalDomain	AppleInterfaceStyleSwitchesAutomatically' \
      $'NSGlobalDomain	NSAutomaticSpellingCorrectionEnabled'
    write_defaults_section "Dock" \
      $'com.apple.dock	autohide' \
      $'com.apple.dock	show-recents' \
      $'com.apple.dock	tilesize'
    write_defaults_section "Finder" \
      $'com.apple.finder	FXPreferredViewStyle' \
      $'com.apple.finder	FXDefaultSearchScope' \
      $'com.apple.finder	NewWindowTargetPath'
    write_defaults_section "Screenshots" \
      $'com.apple.screencapture	location' \
      $'com.apple.screencapture	style' \
      $'com.apple.screencapture	target'
    write_defaults_section "Raycast" \
      $'com.raycast.macos	raycastGlobalHotkey' \
      $'com.raycast.macos	raycastPreferredWindowMode' \
      $'com.raycast.macos	raycastShouldFollowSystemAppearance' \
      $'com.raycast.macos	useHyperKeyIcon'
  } >"$temp_file"

  write_if_changed "$target" "$temp_file"
}

snapshot_app_store() {
  if ! has_command mas; then
    echo "Skipping App Store inventory: mas is missing" >&2
    return
  fi

  local target="$ROOT_DIR/docs/app-store-apps.generated.txt"
  local temp_file
  temp_file="$(mktemp)"

  {
    echo "# Generated by scripts/snapshot.sh --app-store"
    echo
    mas list | sort -k2
  } >"$temp_file"

  write_if_changed "$target" "$temp_file"
}

if [[ "$RUN_BREW" == true ]]; then
  snapshot_brew
fi

if [[ "$RUN_CURSOR" == true ]]; then
  snapshot_cursor_extensions
fi

if [[ "$RUN_RAYCAST" == true ]]; then
  snapshot_raycast_extensions
fi

if [[ "$RUN_MACOS" == true ]]; then
  snapshot_macos_defaults
fi

if [[ "$RUN_APP_STORE" == true ]]; then
  snapshot_app_store
fi
