#!/bin/bash

echo "Installing homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install yadm fish

echo "Installing dotfiles"
yadm clone https://github.com/tjisousa/dotfiles.git

echo "Installing fish"
echo /usr/local/bin/fish | sudo tee -a /etc/shells
chsh -s /usr/local/bin/fish	

echo "Making directories"
mkdir ~/dev

~/bin/update

echo "Installing fisher"
curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
fisher


# Ask if macOS applications should be installed
read -p "Do you want to configure macOS? (yes/no) " mac_config
echo
if [ "$mac_config" == "yes" ]; then
	~/bin/macos
else
	echo "Ok, macOS is not going to be configured."
fi

